In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [2]:
base_path = "/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/Bot-Iot"
rnn_time_series = np.genfromtxt(f"{base_path}/Model/rnn-time-series-y-pred.csv", delimiter=',')
lstm = np.genfromtxt(f"{base_path}/Model/lstm-y-pred.csv", delimiter=',')
rnn = np.genfromtxt(f"{base_path}/Model/rnn-y-pred.csv", delimiter=',')
y_test = np.genfromtxt(f"{base_path}/Sampled/30-sampled-y-test.csv", delimiter=',')

In [3]:
rnn_time_series_df = pd.DataFrame(rnn_time_series, columns = ['rnn_time_series'])
lstm_df = pd.DataFrame(lstm, columns = ['lstm'])
rnn_df = pd.DataFrame(rnn, columns = ['rnn'])

In [4]:
result_df = pd.concat([rnn_time_series_df, lstm_df, rnn_df], axis=1)
result_df

      rnn_time_series  lstm  rnn
0                 1.0   1.0  1.0
1                 0.0   0.0  0.0
2                 0.0   0.0  0.0
3                 0.0   0.0  0.0
4                 0.0   0.0  0.0
...               ...   ...  ...
3902              1.0   1.0  1.0
3903              1.0   1.0  1.0
3904              1.0   1.0  1.0
3905              0.0   0.0  0.0
3906              1.0   1.0  1.0

[3907 rows x 3 columns]

In [5]:
col_list= ['rnn_time_series', 'lstm', 'rnn']
result_df['Sum'] = result_df[col_list].sum(axis=1)
result_df

      rnn_time_series  lstm  rnn  Sum
0                 1.0   1.0  1.0  3.0
1                 0.0   0.0  0.0  0.0
2                 0.0   0.0  0.0  0.0
3                 0.0   0.0  0.0  0.0
4                 0.0   0.0  0.0  0.0
...               ...   ...  ...  ...
3902              1.0   1.0  1.0  3.0
3903              1.0   1.0  1.0  3.0
3904              1.0   1.0  1.0  3.0
3905              0.0   0.0  0.0  0.0
3906              1.0   1.0  1.0  3.0

[3907 rows x 4 columns]

In [10]:
result_df['final'] = result_df['Sum'].apply(lambda x: 1 if x >= 1 else 0)
result_df

      rnn_time_series  lstm  rnn  Sum  final
0                 1.0   1.0  1.0  3.0      1
1                 0.0   0.0  0.0  0.0      0
2                 0.0   0.0  0.0  0.0      0
3                 0.0   0.0  0.0  0.0      0
4                 0.0   0.0  0.0  0.0      0
...               ...   ...  ...  ...    ...
3902              1.0   1.0  1.0  3.0      1
3903              1.0   1.0  1.0  3.0      1
3904              1.0   1.0  1.0  3.0      1
3905              0.0   0.0  0.0  0.0      0
3906              1.0   1.0  1.0  3.0      1

[3907 rows x 5 columns]

In [11]:
final = result_df['final'].to_numpy()
cm = confusion_matrix(y_test, final)
print(cm)
print(classification_report(y_test, final))
print(f"Accuracy: {accuracy_score(y_test, final)}")
print(f"False Positive rate: {1 - (cm[0][1] / len(y_test))}")
print(f"False Negative rate: {1 - (cm[1][0] / len(y_test))}")

[[2721    7]
 [   3 1176]]
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00      2728
         1.0       0.99      1.00      1.00      1179

    accuracy                           1.00      3907
   macro avg       1.00      1.00      1.00      3907
weighted avg       1.00      1.00      1.00      3907

Accuracy: 0.9974404914256463
False Positive rate: 0.9982083439979524
False Negative rate: 0.9992321474276938