In [1]:
import pandas as pd
pd.set_option('display.expand_frame_repr', False)
from sklearn import preprocessing
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
colnames = ['srcip','sport','dstip','dsport','proto','state','dur','sbytes','dbytes','sttl','dttl','sloss','dloss'
                ,'service','Sload','Dload','Spkts','Dpkts','swin','dwin','stcpb','dtcpb','smeansz','dmeansz','trans_depth',
                'res_bdy_len','Sjit','Djit','Stime','Ltime','Sintpkt','Dintpkt','tcprtt','synack','ackdat',
                'is_sm_ips_ports','ct_state_ttl','ct_flw_http_mthd','is_ftp_login','ct_ftp_cmd','ct_srv_src',
                'ct_srv_dst','ct_dst_ltm','ct_src_ ltm','ct_src_dport_ltm','ct_dst_sport_ltm','ct_dst_src_ltm',
                'attack_cat','Label']
df_1 = pd.read_csv("/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/UNSW-NB15/dataset/UNSW-NB15_1.csv", names=colnames, header=None)
df_2 = pd.read_csv("/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/UNSW-NB15/dataset/UNSW-NB15_2.csv", names=colnames, header=None)
df_3 = pd.read_csv("/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/UNSW-NB15/dataset/UNSW-NB15_3.csv", names=colnames, header=None)
df_4 = pd.read_csv("/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/UNSW-NB15/dataset/UNSW-NB15_4.csv", names=colnames, header=None)
data = pd.concat([df_1, df_2, df_3, df_4], ignore_index=True)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (1,3,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: DtypeWarning: Columns (3,39,47) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [3]:
data.shape

(2540047, 49)

In [4]:
dos = data.loc[data['attack_cat'] == 'DoS']
dos.shape

(16353, 49)

In [5]:
normal = data.loc[data['Label'] == 0]
normal.shape

(2218764, 49)

In [ ]:
df = data.drop(['srcip', 'sport', 'dstip', 'dsport'], axis=1)
df

        proto state       dur  sbytes  dbytes  sttl  dttl  sloss  dloss   service  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst  ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  attack_cat  Label
0         udp   CON  0.001055     132     164    31    29      0      0       dns  ...           0           3           7           1            3                 1                 1               1         NaN      0
1         udp   CON  0.036133     528     304    31    29      0      0         -  ...           0           2           4           2            3                 1                 1               2         NaN      0
2         udp   CON  0.001119     146     178    31    29      0      0       dns  ...           0          12           8           1            2                 2                 1               1         NaN      0
3         udp   CON  0.001209     132     164    31    29      0      0       dns  ...           0           6           9           1            1                 1                 1               1         NaN      0
4         udp   CON  0.001169     146     178    31    29      0      0       dns  ...           0           7           9           1            1                 1                 1               1         NaN      0
...       ...   ...       ...     ...     ...   ...   ...    ...    ...       ...  ...         ...         ...         ...         ...          ...               ...               ...             ...         ...    ...
2540042   tcp   FIN  0.087306     320    1828    31    29      1      2  ftp-data  ...                       1           2           3            3                 1                 1               3         NaN      0
2540043   tcp   CON  0.365058     456     346    31    29      2      2       ftp  ...           2           2           2           2            2                 2                 2               2         NaN      0
2540044   tcp   CON  6.335154    1802    2088    31    29      7      9       ftp  ...           2           2           2           4            2                 2                 2               2         NaN      0
2540045   tcp   CON  2.200934    3498  166054    31    29      2     57      http  ...                       1           1           2            4                 2                 2               2         NaN      0
2540046   tcp   CON  0.942984     574     676    62   252      5      6      pop3  ...                       1           1           2            4                 2                 2               2    Exploits      1

[2540047 rows x 45 columns]

In [ ]:
is_NaN = df[['attack_cat']].isnull()
row_has_NaN = is_NaN.any(axis=1)
normal_df = df[row_has_NaN]
normal_df

        proto state       dur  sbytes  dbytes  sttl  dttl  sloss  dloss   service  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst  ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  attack_cat  Label
0         udp   CON  0.001055     132     164    31    29      0      0       dns  ...           0           3           7           1            3                 1                 1               1         NaN      0
1         udp   CON  0.036133     528     304    31    29      0      0         -  ...           0           2           4           2            3                 1                 1               2         NaN      0
2         udp   CON  0.001119     146     178    31    29      0      0       dns  ...           0          12           8           1            2                 2                 1               1         NaN      0
3         udp   CON  0.001209     132     164    31    29      0      0       dns  ...           0           6           9           1            1                 1                 1               1         NaN      0
4         udp   CON  0.001169     146     178    31    29      0      0       dns  ...           0           7           9           1            1                 1                 1               1         NaN      0
...       ...   ...       ...     ...     ...   ...   ...    ...    ...       ...  ...         ...         ...         ...         ...          ...               ...               ...             ...         ...    ...
2540041   tcp   CON  0.564998   14106  772406    31    29      2    262         -  ...                       2           1           4            2                 2                 2               2         NaN      0
2540042   tcp   FIN  0.087306     320    1828    31    29      1      2  ftp-data  ...                       1           2           3            3                 1                 1               3         NaN      0
2540043   tcp   CON  0.365058     456     346    31    29      2      2       ftp  ...           2           2           2           2            2                 2                 2               2         NaN      0
2540044   tcp   CON  6.335154    1802    2088    31    29      7      9       ftp  ...           2           2           2           4            2                 2                 2               2         NaN      0
2540045   tcp   CON  2.200934    3498  166054    31    29      2     57      http  ...                       1           1           2            4                 2                 2               2         NaN      0

[2218764 rows x 45 columns]

In [ ]:
df_ddos = df.loc[data['attack_cat'] == 'DoS']
df_ddos

        proto state       dur  sbytes  dbytes  sttl  dttl  sloss  dloss service  ...  ct_ftp_cmd  ct_srv_src  ct_srv_dst  ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm  attack_cat  Label
57        tcp   FIN  0.177449    1214     268   254   252      2      1    http  ...           0           5           2           1            1                 1                 1               1         DoS      1
78        tcp   FIN  2.592910    2082     268   254   252      6      1    http  ...           0           5           2           1            2                 2                 1               1         DoS      1
198       tcp   FIN  0.268272     878    1002    62   252      2      2    http  ...           0           3           1           1            1                 1                 1               1         DoS      1
1565      tcp   FIN  0.214066     468     268   254   252      2      1       -  ...           0           1           1           1            1                 1                 1               1         DoS      1
1877      udp   INT  0.000021     136       0   254     0      0      0    snmp  ...           0           1           1           1            1                 1                 1               1         DoS      1
...       ...   ...       ...     ...     ...   ...   ...    ...    ...     ...  ...         ...         ...         ...         ...          ...               ...               ...             ...         ...    ...
2539261   tcp   FIN  1.770885    2641    1802    62   252      8      8    smtp  ...                       1           1           3            1                 1                 1               1         DoS      1
2539348   tcp   FIN  1.445151   86346    2292    62   252     37      8    smtp  ...                       1           1           1            1                 1                 1               1         DoS      1
2539948   tcp   FIN  2.358193  330718    1816    62   252    126      1       -  ...                       1           1           1            1                 1                 1               1         DoS      1
2540029   tcp   CON  2.579405  269883    1300    62   252    103      1       -  ...                       2           1           2            4                 2                 2               2         DoS      1
2540030   tcp   CON  2.579405  269883    1300    62   252    103      1    http  ...                       1           1           2            4                 2                 2               2         DoS      1

[16353 rows x 45 columns]

In [ ]:
normal_attack_rate = 0.3
attcak_row_size = df_ddos.shape[0]*0.7/0.3
attcak_row_size

38157.0

In [ ]:
sampled_normal = normal_df.sample(int(attcak_row_size),replace=True)
sampled_normal.shape

(38157, 45)

In [ ]:
sampled_df = pd.concat([sampled_normal, df_ddos])
sampled_df = sampled_df.sort_index()
sampled_df_label = sampled_df['Label']
sampled_df = sampled_df.drop(['attack_cat', 'ct_ftp_cmd','Label'], axis=1)
sampled_df

        proto state       dur  sbytes  dbytes  sttl  dttl  sloss  dloss service  ...  ct_state_ttl  ct_flw_http_mthd  is_ftp_login  ct_srv_src  ct_srv_dst  ct_dst_ltm  ct_src_ ltm  ct_src_dport_ltm  ct_dst_sport_ltm  ct_dst_src_ltm
11        arp   INT  0.000000      46       0     0     0      0      0       -  ...             2               0.0           0.0           2           2           2            2                 2                 2               2
54        udp   CON  0.001112     132     164    31    29      0      0     dns  ...             0               0.0           0.0           6           8           1            1                 1                 1               1
57        tcp   FIN  0.177449    1214     268   254   252      2      1    http  ...             1               1.0           0.0           5           2           1            1                 1                 1               1
72        udp   CON  0.001118     132     164    31    29      0      0     dns  ...             0               0.0           0.0          12           8           5            3                 3                 2               2
78        tcp   FIN  2.592910    2082     268   254   252      6      1    http  ...             1               1.0           0.0           5           2           1            2                 2                 1               1
...       ...   ...       ...     ...     ...   ...   ...    ...    ...     ...  ...           ...               ...           ...         ...         ...         ...          ...               ...               ...             ...
2539801   udp   CON  0.004521     568     304    31    29      0      0       -  ...             0               NaN           NaN           7           7           3            6                 1                 1               3
2539948   tcp   FIN  2.358193  330718    1816    62   252    126      1       -  ...             1               1.0           NaN           1           1           1            1                 1                 1               1
2539991   tcp   FIN  0.024905    3614   44706    31    29      7     24       -  ...             0               NaN           NaN           6           3           4            4                 1                 1               1
2540029   tcp   CON  2.579405  269883    1300    62   252    103      1       -  ...             3               2.0           NaN           2           1           2            4                 2                 2               2
2540030   tcp   CON  2.579405  269883    1300    62   252    103      1    http  ...             3               2.0           NaN           1           1           2            4                 2                 2               2

[54510 rows x 42 columns]

In [ ]:
service_categorical_cols = pd.get_dummies(sampled_df['service'], prefix='service', prefix_sep='_', dummy_na=False, columns=['service'], sparse=False, drop_first=False, dtype=None)
state_categorical_cols = pd.get_dummies(sampled_df['state'], prefix='state', prefix_sep='_', dummy_na=False, columns=['state'], sparse=False, drop_first=False, dtype=None)
proto_categorical_cols = pd.get_dummies(sampled_df['proto'], prefix='proto', prefix_sep='_', dummy_na=False, columns=['proto'], sparse=False, drop_first=False, dtype=None)

In [ ]:
sampled_df = sampled_df.drop(['service', 'state', 'proto'], axis=1)
sampled_df_2 = pd.concat([sampled_df, service_categorical_cols, state_categorical_cols, proto_categorical_cols],axis=1)
sampled_df_2.shape

(54510, 193)

In [ ]:
x = sampled_df_2.values #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df = pd.DataFrame(x_scaled)
df2 = df.fillna(0)

In [ ]:
df2.reset_index(inplace=True, drop=True)
sampled_df_label.reset_index(inplace=True, drop=True)
final_df = pd.concat([df2, sampled_df_label], axis=1)
final_df

              0         1         2         3         4         5         6         7         8         9  ...  184  185  186  187  188  189  190  191  192  Label
0      0.000000  0.000002  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0
1      0.000019  0.000009  0.000011  0.121569  0.114173  0.000000  0.000000  0.000090  0.027638  0.000115  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0
2      0.002958  0.000102  0.000018  0.996078  0.992126  0.000475  0.000182  0.000009  0.000473  0.001038  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      1
3      0.000019  0.000009  0.000011  0.121569  0.114173  0.000000  0.000000  0.000090  0.027490  0.000115  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0
4      0.043216  0.000177  0.000018  0.996078  0.992126  0.001425  0.000182  0.000001  0.000032  0.001500  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      1
...         ...       ...       ...       ...       ...       ...       ...       ...       ...       ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...
54505  0.000075  0.000047  0.000021  0.121569  0.114173  0.000000  0.000000  0.000143  0.018902  0.000346  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0
54506  0.039304  0.028432  0.000124  0.243137  0.992126  0.029929  0.000182  0.000212  0.000282  0.029649  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      1
54507  0.000415  0.000309  0.003050  0.121569  0.114173  0.001663  0.004358  0.000217  0.661933  0.006807  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      0
54508  0.042991  0.023201  0.000089  0.243137  0.992126  0.024466  0.000182  0.000158  0.000183  0.023881  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      1
54509  0.042991  0.023201  0.000089  0.243137  0.992126  0.024466  0.000182  0.000158  0.000183  0.023881  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0      1

[54510 rows x 194 columns]

In [ ]:
final_df.to_csv (r'/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/UNSW-NB15/dataset/30-sampled-data.csv', header=True)

In [ ]:
base_path = "/content/drive/MyDrive/Okul/İTÜ/Bilgisayar Mühendisliği Yüksek Lisans/Yüksek Lisans/YL Tez/Development/UNSW-NB15/dataset"
data = pd.read_csv(f"{base_path}/30-sampled-data.csv", index_col=0)
data = data.fillna(0)
X = data.iloc[:, 1:-1]
y = data.iloc[:, -1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=69)

In [ ]:
np.savetxt(f"{base_path}/30-sampled-x-train.csv", X_train, delimiter=",")
np.savetxt(f"{base_path}/30-sampled-y-train.csv", y_train, delimiter=",")
np.savetxt(f"{base_path}/30-sampled-x-test.csv", X_test, delimiter=",")
np.savetxt(f"{base_path}/30-sampled-y-test.csv", y_test, delimiter=",")